services:
  api:
    build: .
    depends_on:
      database:
        condition: service_healthy
        restart: true
    ports:
      - "0.0.0.0:8000:8000"
    environment:
      BOSWACHTER_DB_URL: "postgresql://boswachter:highsecurity@database:5432/boswachter"
    develop:
      watch:
        - action: sync+restart
          path: ./app
          target: /code/app

  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: highsecurity
      POSTGRES_USER: boswachter
      POSTGRES_DB: boswachter
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s